### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by conklech** [sonyhome/FAB_LED#29]
This repository has a copy of the GPL as "LICENSES," which is the standard way to indicate that the contents are licensed under the GPL. But FAB_LED.h has a comment at the top: "Licence: limited use is authorized for the purpose of beta testing." That statement isn't consistent with the GPL. Which is it? Are others allowed to modify, use, and redistribute this code like the GPL permits, or are we only allowed to use it (unmodified?) for beta testing? I'd quite like to use this library as part of a bigger open-source project, but I can't unless it's got a clear license that's compatible with the license covering the rest of the project.

Also, I'd encourage you to consider changing the license to MIT (which FastLED uses), LGPL 3.0 (which Adafruit_NeoPixel uses), or at the very least GPL 3.0. The choice of license is obviously yours to make, but GPL 2.0 code is incompatible with virtually all of the other licenses out there; it can't even be used in a GPL 3.0 project. If copyleft is important to you, LGPL preserves that for your code, while making it open to a much wider audience. There's a summary of various licenses at https://choosealicense.com/, which seems pretty good. (But their frontpage description of GPL is wrong: it doesn't just prohibit distributing closed-source programs, it prohibits using the code in anything that's not licensed under the same GPL license, which none of the other common licenses require.)

**Comment by sonyhome** [comment]
Sorry for the long delay.

I am not too uptight on the license, and do not plan to make a profit on this project.
I would be OK to switch to an MIT license (I'd have to do a quick read).

**Comment by sonyhome** [comment]
The licence has been changed to be as permissive as possible.
